# Generated by Django 3.2.9 on 2022-03-20 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Properti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], max_length=50)),
                ('ptype', models.CharField(choices=[('Home', 'Home'), ('Land', 'Land'), ('Room', 'Room')], max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('number_of_rooms', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('has_installment', models.BooleanField(default=False)),
                ('has_insurance', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=455)),
                ('garden', models.BooleanField(default=False)),
                ('garage', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('bathtub', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('play_ground', models.BooleanField(default=False)),
                ('video', models.URLField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='prop/%Y/%m/%d')),
                ('paid', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('seodescription', models.TextField(blank=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-paid', '-timestamp'],
            },
        ),
    ]
