# Generated by Django 3.2.9 on 2022-04-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='properti',
            name='bidding_end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='properti',
            name='status',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale'), ('Auction', 'Auction')], max_length=50),
        ),
    ]
