# Generated by Django 3.1.4 on 2022-04-05 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realestate', '0004_auto_20220404_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank_image', models.ImageField(upload_to='prop/%Y/%m/%d')),
                ('Bank_name', models.CharField(max_length=50)),
                ('Phone_number', models.CharField(max_length=50)),
                ('Rate', models.IntegerField()),
                ('Tenure', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='bidders',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bidders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bidder_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='properti',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
