# Generated by Django 3.1.4 on 2022-04-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0008_auto_20220406_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyagent',
            name='Agency_logo',
        ),
    ]
