# Generated by Django 3.1.4 on 2022-04-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0009_remove_applyagent_agency_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyagent',
            name='Agency_logo',
            field=models.ImageField(default=1, upload_to='prop/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
