# Generated by Django 3.1.4 on 2022-04-07 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0010_applyagent_agency_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyagent',
            name='Agency_logo',
        ),
    ]
