# Generated by Django 3.1.4 on 2022-04-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0011_remove_applyagent_agency_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyagent',
            name='Agency_logo',
            field=models.ImageField(blank=True, null=True, upload_to='prop/%Y/%m/%d'),
        ),
    ]
