# Generated by Django 3.2.9 on 2022-04-09 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realestate', '0013_auto_20220409_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyagent',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='accounts.account'),
            preserve_default=False,
        ),
    ]
