# Generated by Django 3.2.9 on 2022-04-09 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realestate', '0015_alter_applyagent_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('agent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_of_agent', to='realestate.applyagent')),
                ('rating_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_rater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
